### PR TITLE
rework the Makefile

### PR DESCRIPTION
**Pull request by hasufell**
please see the comments in both commits

### CODE REVIEW

**Comment by DDR0** [comment]
Accepted, with changes. The pkg-config code didn't work on my computer, SDL_ttf among others being undefined, and changed the optimization code to default to on. Thank you.

**Comment by hasufell** [comment]
that's fine, thanks!

**Comment by hasufell** [comment]
regarding the failing pkg-config stuff you could do:

$(shell pkg-config --libs SDL_image SDL_ttf 2>/dev/null || echo "-lSDL_ttf -lSDL_mixer")

which is backwards compatible.

Also I noticed we don't use "pkg-config --cflags" for the corresponding libs. This is not always neccessary, but depending on the distribution we might need the "-I/some/dir/to/header/files" flags which we get by this pkg-config call too.

**Comment by DDR0** [comment]
Oh, I like that. :)

So, we've got

LIBS += $(shell pkg-config --libs x11 ) \
    -lSDLmain -lSDL_ttf -lSDL_mixer \
    $(shell pkg-config --libs sdl glu glew SDL_image libpng zlib) \

right now. So,

LIBS += $(shell pkg-config --libs x11 ) \
    -lSDLmain \
    $(shell pkg-config --libs sdl glu glew SDL_image libpng zlib) \
    $(shell pkg-config --libs SDL_image SDL_ttf 2>/dev/null || echo "-lSDL_ttf -lSDL_mixer") \
    $(shell pkg-config --cflags)" \

would be the new version?

**Comment by hasufell** [comment]
nope, it would be 

CFLAGS += (shell pkg-config --cflags x11 ) \
$(shell pkg-config --cflags sdl glu glew SDL_image libpng zlib) \
$(shell pkg-config --cflags SDL_image SDL_ttf 2>/dev/null)

LIBS += $(shell pkg-config --libs x11 ) \
-lSDLmain \
$(shell pkg-config --libs sdl glu glew SDL_image libpng zlib) \
$(shell pkg-config --libs SDL_image SDL_ttf 2>/dev/null || echo "-lSDL_ttf -lSDL_mixer")

It is also possible to do "--cflags-only-I" instead of "--cflags", but I would only do that if some pkg-config file really adds weird flags.

**Comment by DDR0** [comment]
That's not suppose to be CPPFLAGS += … there?

**Comment by hasufell** [comment]
doesn't much matter really.

"pkg-config --cflags" actually may add preprocessor flags as well as compiler flags. You never know unless you call it (or you use the mentioned "--cflags-only-I" which is a bit over-finegraining here IMO)

**Comment by DDR0** [comment]
OK. Thanks for the advice, hasufell. :)

**Pull request merged**
